version: '3.9'

services:
  mongodb:
    image: mongo:7.0.4-jammy
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: isyll
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: