version: '3.9'

services:
  postgres:
    image: postgres:16.1-alpine
    container_name: postgresql
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=admin
      - POSTGRES_DB=chat_db
  pgadmin:
    image: dpage/pgadmin4:8.1
    container_name: pgadmin4
    restart: always
    ports:
      - 7998:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: