version: '3.9'

services:
  mongodb:
    image: mongo:7.0.4-jammy
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: isyll
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:1.0.0-18-alpine3.18
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: isyll
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: isyll
      ME_CONFIG_BASICAUTH_PASSWORD: secret
    ports:
      - 7798:8081
    depends_on:
      - mongodb

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.3
    container_name: keycloak
    ports:
      - 8800:8080
    environment:
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
    command: start-dev

volumes:
  mongodb_data: