server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: chat
          uri: lb://chat
          predicates:
            - Path=/chat/**
          filters:
            - AddResponseHeader=X-Powered-By,Api-gateway
            - StripPrefix=1
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - AddResponseHeader=X-Powered-By,Api-gateway
            - StripPrefix=1

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
